default:
  image: python:3.8-slim

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'main'

stages:
  - Static Analysis
  - Install
  - Documentation
  - Test
  - Ship

# -------------------------- Static analysis -----------------------------------

.static_analysis_base:
  stage: Static Analysis
  allow_failure: true

flake8:
  extends: .static_analysis_base
  script:
    - pip install flake8
    - flake8 $PWD/theia_picker

pylint:
  extends: .static_analysis_base
  script:
    - pip install pylint requests pydantic urllib3 tqdm
    - pylint $PWD/theia_picker

codespell:
  extends: .static_analysis_base
  script: 
    - pip install codespell
    - codespell $PWD/theia_picker

# ----------------------------- Install ----------------------------------------

pip_install:
  stage: Install
  script:
    - pip install .

# ------------------------------- Doc ------------------------------------------

.doc_base:
  stage: Documentation
  before_script:
    - pip install mkdocstrings mkdocstrings[crystal,python] mkdocs-material mkdocs-gen-files mkdocs-section-index mkdocs-literate-nav mkdocs-mermaid2-plugin --upgrade
  artifacts:
    paths:
      - public
      - public_test

pages_tests:
  extends: .doc_base
  except:
   - main
  script:
    - mkdocs build --site-dir public_test

pages:
  extends: .doc_base
  only:
   - main
  script:
    - mkdocs build --site-dir public

# -------------------------------- Tests ---------------------------------------

#tests:
#  stage: Test
#  allow_failure: false
#  script:
#    - pip install .
#    - python tests/download_test.py

# --------------------------------- Ship ---------------------------------------

pypi:
  stage: Ship
  only:
   - main
  before_script:
   - python3 -m pip install --upgrade build twine
  script:
   - python3 -m build
  after_script:
   - python3 -m twine upload --repository-url https://upload.pypi.org/legacy/ --non-interactive -u __token__ -p $pypi_token dist/*
